version: '3.8'

services:
  bot:
    build:
      context: .
    stop_signal: SIGINT
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    restart: always
volumes:
    postgres_data: